/* eslint no-magic-numbers: 0 */
'use strict';

module.exports = {
  rules: {
    'array-bracket-spacing': [2, 'never'],
    'block-spacing': [2, 'always'],
    'brace-style': [2, 'stroustrup', {allowSingleLine: false}],
    'camelcase': [2, {properties: 'always'}],
    'comma-spacing': [2, {before: false, after: true}],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': [2, 'self'],
    'eol-last': 2,
    'func-names': 0,
    'func-style': 0,
    'id-length': [2, {
      min: 2,
      max: 35,
      properties: 'always',
      exceptions: ['_', 'i']
    }],
    'id-match': 0,
    'indent': [2, 2],
    'jsx-quotes': [2, 'prefer-double'],
    'key-spacing': [2, {beforeColon: false, afterColon: true}],
    'linebreak-style': [2, 'unix'],
    'lines-around-comment': [2, {
      beforeBlockComment: true,
      afterBlockComment: false,
      beforeLineComment: true,
      afterLineComment: false,
      allowBlockStart: true,
      allowBlockEnd: false,
      allowObjectStart: true,
      allowObjectEnd: false,
      allowArrayStart: true,
      allowArrayEnd: false
    }],
    'max-depth': [2, 3],
    'max-len': [2, 80, 4],
    'max-nested-callbacks': [2, 3],
    'max-params': [2, 4],
    'max-statements': [2, 25],
    'new-cap': [2, {newIsCap: true, capIsNew: true}],
    'new-parens': 2,
    'newline-after-var': 0,
    'no-array-constructor': 2,
    'no-bitwise': 2,
    'no-continue': 2,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': [2, {max: 1, maxEOF: 1}],
    'no-negated-condition': 2,
    'no-nested-ternary': 2,
    'no-new-object': 2,
    'no-plusplus': [2, {allowForLoopAfterthoughts: true}],
    'no-restricted-syntax': [2, 'WithStatement'],
    'no-spaced-func': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 2,
    'no-unneeded-ternary': 2,
    'object-curly-spacing': [2, 'never'],
    'one-var': [2, 'never'],
    'operator-assignment': [2, 'always'],
    'operator-linebreak': [2, 'after'],
    'padded-blocks': [2, 'never'],
    'quote-props': [2, 'consistent-as-needed', {keywords: true}],
    'quotes': [2, 'single', 'avoid-escape'],
    'require-jsdoc': 0,
    'semi-spacing': [2, {before: false, after: true}],
    'semi': [2, 'always'],
    'sort-vars': [2, {ignoreCase: false}],
    'space-after-keywords': [2, 'always'],
    'space-before-blocks': 2,
    'space-before-function-paren': [2, 'never'],
    'space-before-keywords': [2, 'always'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': [2, {int32Hint: false}],
    'space-return-throw-case': 2,
    'space-unary-ops': [2, {words: true, nonwords: false}],
    'spaced-comment': [2, 'always'],
    'wrap-regex': 2
  }
};
